### ISSUE TITLE
Flux Install

### ISSUE THREAD

**Issue by aflyingcougar** [aflyingcougar/homelab#16]
Document the old method of FluxCD installation, so that it can be adapted to the modern version using the `flux bootstrap` command.

## `task cluster:install`
1. `kubectl apply --kustomize` on `./kubernetes/bootstrap`

Contents of `.kubernetes/bootstrap`:
`kustomization.yaml`
```
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - github.com/fluxcd/flux2/manifests/install?ref=v2.2.3
patches:
  # Remove the network policies that do not work with k3s
  - patch: |-
      $patch: delete
      apiVersion: networking.k8s.io/v1
      kind: NetworkPolicy
      metadata:
        name: not-used
    target:
      group: networking.k8s.io
      version: v1
      kind: NetworkPolicy
```
The referenced resources from the v.2.2.3 Tag in the `fluxcd/flux2` repository at `./manifests/install/`:
### `kustomization.yaml`
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - namespace.yaml
  - ../bases/source-controller
  - ../bases/kustomize-controller
  - ../bases/notification-controller
  - ../bases/helm-controller
  - ../bases/image-reflector-controller
  - ../bases/image-automation-controller
  - ../rbac
  - ../policies
transformers:
  - labels.yaml
images:
  - name: fluxcd/source-controller
    newName: ghcr.io/fluxcd/source-controller
  - name: fluxcd/kustomize-controller
    newName: ghcr.io/fluxcd/kustomize-controller
  - name: fluxcd/helm-controller
    newName: ghcr.io/fluxcd/helm-controller
  - name: fluxcd/notification-controller
    newName: ghcr.io/fluxcd/notification-controller
  - name: fluxcd/image-reflector-controller
    newName: ghcr.io/fluxcd/image-reflector-controller
  - name: fluxcd/image-automation-controller
    newName: ghcr.io/fluxcd/image-automation-controller
```
### `labels.yaml`
```
apiVersion: builtin
kind: LabelTransformer
metadata:
  name: labels
labels:
  app.kubernetes.io/part-of: flux
  app.kubernetes.io/instance: flux-system
fieldSpecs:
  - path: metadata/labels
    create: true
```
### `namespace.yaml`
```
apiVersion: v1
kind: Namespace
metadata:
  name: flux-system
  labels:
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/warn-version: latest
```

2. `cat {{.SOPS_AGE_KEY_FILE}} | kubectl -n flux-system create secret generic sops-age --from-file=age.agekey=/dev/stdin`

3. `sops --decrypt {{.KUBERNETES_DIR}}/flux/vars/cluster-secrets.sops.yaml | kubectl apply -f -`

4. `kubectl apply -f {{.KUBERNETES_DIR}}/flux/vars/cluster-settings.yaml`

5. `kubectl apply --kustomize {{.KUBERNETES_DIR}}/flux/config`
Contents of `./kubernetes/flux/config/`:
### `kustomization.yaml`
```
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./flux.yaml
  - ./cluster.yaml

```

### `flux.yaml`
```
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: flux-manifests
  namespace: flux-system
spec:
  interval: 10m
  url: oci://ghcr.io/fluxcd/flux-manifests
  ref:
    tag: v2.2.3
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux
  namespace: flux-system
spec:
  interval: 10m
  path: ./
  prune: true
  wait: true
  sourceRef:
    kind: OCIRepository
    name: flux-manifests
  patches:
    - patch: |
        $patch: delete
        apiVersion: networking.k8s.io/v1
        kind: NetworkPolicy
        metadata:
          name: not-used
      target:
        group: networking.k8s.io
        version: v1
        kind: NetworkPolicy
    - patch: |
        - op: add
          path: /spec/template/spec/containers/0/args/-
          value: --concurrent=8
        - op: add
          path: /spec/template/spec/containers/0/args/-
          value: --kube-api-qps=500
        - op: add
          path: /spec/template/spec/containers/0/args/-
          value: --kube-api-burst=1000
        - op: add
          path: /spec/template/spec/containers/0/args/-
          value: --requeue-dependency=5s
      target:
        kind: Deployment
        name: "(kustomize-controller|helm-controller|source-controller)"

```

### `cluster.yaml`
```
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: home-kubernetes
  namespace: flux-system
spec:
  interval: 30m
  ref:
    branch: "main"
  url: "https://github.com/aflyingcougar/homelab"
  ignore: |
    # exclude all
    /*
    # include kubernetes directory
    !/kubernetes
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster
  namespace: flux-system
spec:
  interval: 30m
  path: ./kubernetes/flux
  prune: true
  wait: false
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
      - kind: Secret
        name: cluster-secrets

```
